auto=read.csv("C:/Users/gadda/Downloads/Auto.csv")
head(auto)
auto$origin[auto$origin == 1] = "American"
auto$origin[auto$origin == 2] = "European"
auto$origin[auto$origin == 3] = "Japanese"
auto$origin = as.factor(auto$origin)
head(auto)
pairs(~mpg + cylinders + displacement + horsepower + weight + acceleration + year, auto)
cor(auto[,-c(8, 9)])
mpg.fit = lm(mpg ~ . - name, data = auto)
summary(mpg.fit)
contrasts(auto$origin)
library(car)
vif(lm(mpg ~ . - origin - name, data = auto))
par(mfrow = c(2, 2))
plot(mpg.fit)
mpg.fit.all.interactions = lm(mpg ~ (. - name)^2, data = Auto)
summary(mpg.fit.all.interactions)
mpg.fit.reduced.interactions = update(mpg.fit.all.interactions, ~ . - horsepower:origin)
summary(mpg.fit.reduced.interactions)
mpg.fit.reduced.interactions = update(mpg.fit.reduced.interactions, ~ . - displacement:horsepower)
summary(mpg.fit.reduced.interactions)
mpg.fit.reduced.interactions = update(mpg.fit.reduced.interactions, ~ . - weight:acceleration)
summary(mpg.fit.reduced.interactions)
mpg.fit.reduced.interactions = update(mpg.fit.reduced.interactions, ~ . - weight:year)
summary(mpg.fit.reduced.interactions)mpg.fit.reduced.interactions = update(mpg.fit.reduced.interactions, ~ . - cylinders:horsepower)
summary(mpg.fit.reduced.interactions)
mpg.fit.reduced.interactions = update(mpg.fit.reduced.interactions, ~ . + cylinders:origin - displacement:acceleration)
summary(mpg.fit.reduced.interactions)
par(mfrow = c(2, 2))
plot(Auto$displacement, Auto$mpg)
plot(Auto$horsepower, Auto$mpg)
plot(Auto$weight, Auto$mpg)
plot(Auto$acceleration, Auto$mpg)
summary(lm(mpg ~ acceleration, data = Auto))
par(mfrow = c(2, 2))
plot(lm(mpg ~ acceleration, data = Auto))
summary(lm(mpg ~ log(acceleration), data = Auto))
par(mfrow = c(2, 2))
plot(lm(mpg ~ log(acceleration), data = Auto))
displacement.linear = lm(mpg ~ displacement, data = Auto)
summary(displacement.linear)
anova(displacement.quadratic, displacement.quintic)
