auto=read.csv("C:/Users/gadda/Downloads/Auto.csv")
auto = na.omit(auto)
auto.lin.fit = lm(mpg ~ horsepower, data = auto)
summary(auto.lin.fit)
head(auto)
dim(auto)
plot(auto$horsepower, auto$mpg, xlab = "Horsepower", ylab = "Miles per gallon")
abline(auto.lin.fit, lwd = 3, col = "red")
par(mfrow = c(2, 2))
plot(auto.lin.fit)
