auto=read.csv("C:/Users/gadda/Downloads/Auto.csv")
summary(auto)
sapply(auto[,c(1:6),],range)
sapply(auto[,c(1:6),],mean)
sapply(auto[,c(1:6),],sd)
new.auto=subset(auto[-c(10:85),])
sapply(new.auto[,-c(9)],range)
sapply(new.auto[,-c(9)],mean)
sapply(new.auto[,-c(9)],sd)
par(mfrow = c(2, 2))
plot(auto$displacement, auto$mpg, xlab = "Engine displacement (cubic inches)", ylab = "Miles per gallon")
plot(auto$horsepower, auto$mpg, xlab = "Horsepower", ylab = "Miles per gallon")
plot(auto$weight, auto$mpg, xlab = "Car weight (pounds)", ylab = "Miles per gallon")
plot(auto$year, auto$mpg, xlab = "Model Year", ylab = "Miles per gallon")
par(mfrow = c(2, 2))
plot(auto$year, auto$acceleration, xlab = "Model Year", ylab = "0 to 60mph time (seconds)")
plot(auto$year, auto$displacement, xlab = "Model Year", ylab = "Engine displacement (cubic inches)")
plot(auto$year, auto$weight, xlab = "Model Year", ylab = "Car weight (pounds)")
plot(auto$year, auto$horsepower, xlab = "Model Year", ylab = "Horsepower")
par(mfrow = c(2, 2))
plot(auto$weight, auto$acceleration, xlab = "Car weight (pounds)", ylab = "0 to 60mph time (seconds)")
plot(auto$cylinders, auto$acceleration, xlab = "Number of engine cylinders", ylab = "0 to 60mph time (seconds)")
plot(auto$displacement, auto$acceleration, xlab = "Engine displacement (cubic inches)", ylab = "0 to 60mph time (seconds)")
plot(auto$horsepower, auto$acceleration, xlab = "Horsepower", ylab = "0 to 60mph time (seconds)")
par(mfrow = c(2, 1))
plot(auto$weight, auto$horsepower, xlab = "Car weight (pounds)", ylab = "Horsepower")
plot(auto$weight, auto$displacement, xlab = "Car weight (pounds)", ylab = "Engine displacement (cubic inches)")
plot(factor(auto$origin),auto$mpg,names=(c("American","European","Japanese")))

