library(MASS)
Boston
head(Boston)
dim(Boston)
par(mfrow = c(2, 2))
head(Boston)
plot(Boston$age, Boston$medv, xlab = "Percent of units built prior to 1940", ylab = "Median home value in $1000s")
plot(Boston$lstat, Boston$medv, xlab = "Percent of lower status residents", ylab = "Median home value in $1000s")
plot(Boston$medv, Boston$ptratio, xlab = "Median home value in $1000s", ylab = "Pupil-teacher ratio")
plot(as.factor(Boston$chas), Boston$medv, xlab = "Borders Charles River", ylab = "Median home value in $1000s")
par(mfrow = c(2, 2))
plot(Boston$medv, Boston$nox, xlab = "Median home value in $1000s", ylab = "Nitric oxides concentration (parts per 10 million)")
plot(Boston$indus, Boston$nox, xlab = "Percent of non-retail business acres", ylab = "Nitric oxides concentration (parts per 10 million)")
plot(Boston$medv, Boston$black, xlab = "Median home value in $1000s", ylab = "1000(Proportion of black residents - 0.63)^2")
plot(Boston$dis, Boston$medv, xlab = "Weighted distance to Boston employment centers", ylab = "Median home value in $1000s")
par(mfrow = c(2, 2))
plot(Boston$black, Boston$crim, xlab = "1000(Proportion of black residents - 0.63)^2", ylab = "Per capita crime rate")
plot(Boston$lstat, Boston$crim, xlab = "Percent of lower status residents", ylab = "Per capita crime rate")
plot(Boston$medv, Boston$crim, xlab = "Median home value in $1000s", ylab = "Per capita crime rate")
plot(Boston$dis, Boston$crim, xlab = "Weighted distance to Boston employment centers", ylab = "Per capita crime rate")
par(mfrow = c(2, 2))
hist(Boston$crim, xlab = "Per capita crime rate", main = "Histogram of Boston crime rates")
hist(Boston$tax, xlab = "Tax rate per 10000 USD", main = "Histogram of Boston tax rates")
hist(Boston$ptratio, xlab = "Pupil-teacher ratio", main = "Histogram of Boston pupil-teacher ratios")
summary(Boston[,c(8, 13, 14)])
table(Boston$chas)
median(Boston$ptratio)
min(Boston$medv)
Boston[Boston$medv == 5, ]
summary(Boston[, c(8:10, 12:14)])
table(Boston$rm > 7)
table(Boston$rm > 8)
Boston[Boston$rm > 8, ]
summary(Boston[Boston_corrected$RM > 8, c(7:10, 12:14)])

